### ISSUE TITLE
java.lang.NumberFormatException: For input string: "10000;"

### ISSUE THREAD

**Issue by alcarola** [maths/stack_util_maximapool#7]
Hi!

I post a bug report here, but maybe I should send it to aharjula instead?

I tried compiling and installing the maxima pool according to the instructions. I only changed the maxima binary path and the path for maximalocal.mac. These files both have some optimization included.

I compiled a dedicated tomcat for the maxima pool, but was unable to make it run, so I installed the maxima pool in a red5/tomcat server that I already have for another application. I went to localhost:5080/MaximaPool/MaximaPool and I got the errors below.

Friendly greetings,
Mikael

--- 8< ---

java.lang.NumberFormatException: For input string: "10000;"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48) ~[na:1.6.0_38]
        at java.lang.Long.parseLong(Long.java:419) ~[na:1.6.0_38]
        at java.lang.Long.parseLong(Long.java:468) ~[na:1.6.0_38]
        at fi.aalto.maximapool.MaximaProcessConfig.loadProperties(MaximaProcessConfig.java:97) ~[MaximaProcessConfig.class:na]
        at fi.aalto.maximapool.MaximaServlet.init(MaximaServlet.java:77) ~[MaximaServlet.class:na]
        at javax.servlet.GenericServlet.init(GenericServlet.java:212) ~[javaee-api-5.1.2.om.jar:na]
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:809) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:129) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:554) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) [catalina-6.0.32.jar:6.0.32]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859) [tomcat-coyote-6.0.32.jar:6.0.32]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588) [tomcat-coyote-6.0.32.jar:6.0.32]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) [tomcat-coyote-6.0.32.jar:6.0.32]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_38]
2013-01-04 13:52:30,529 [http-0.0.0.0-5080-1] ERROR o.a.c.c.C.[.[.0.0.0.[.[MaximaPool] - Allocate exception for servlet MaximaPool
java.lang.NumberFormatException: For input string: "10000;"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48) ~[na:1.6.0_38]
        at java.lang.Long.parseLong(Long.java:419) ~[na:1.6.0_38]
        at java.lang.Long.parseLong(Long.java:468) ~[na:1.6.0_38]
        at fi.aalto.maximapool.MaximaProcessConfig.loadProperties(MaximaProcessConfig.java:97) ~[MaximaProcessConfig.class:na]
        at fi.aalto.maximapool.MaximaServlet.init(MaximaServlet.java:77) ~[MaximaServlet.class:na]
        at javax.servlet.GenericServlet.init(GenericServlet.java:212) ~[javaee-api-5.1.2.om.jar:na]
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173) ~[catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:809) ~[catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:129) ~[catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:554) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina-6.0.32.jar:6.0.32]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) [catalina-6.0.32.jar:6.0.32]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859) [tomcat-coyote-6.0.32.jar:6.0.32]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588) [tomcat-coyote-6.0.32.jar:6.0.32]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) [tomcat-coyote-6.0.32.jar:6.0.32]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_38]

**Comment by musman03** [comment]
I am facing the same exception kindly let me know in which file this value need to be change??Exception is given below

log4j:ERROR [1000K] is not in proper int form.
log4j:ERROR [1000K] not in expected format.
java.lang.NumberFormatException: For input string: "1000K"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.valueOf(Long.java:540)
        at org.apache.log4j.helpers.OptionConverter.toFileSize(OptionConverter.java:270)
        at org.apache.log4j.RollingFileAppender.setMaxFileSize(RollingFileAppender.java:218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:205)
        at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:164)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:129)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:96)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:654)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:612)
        at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:533)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:417)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:441)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:468)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
        at org.apache.log4j.Logger.getLogger(Logger.java:103)
        at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:229)
        at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:65)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:529)
        at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:235)
        at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:209)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351)
        at org.apache.struts.action.ActionServlet.<clinit>(ActionServlet.java:375)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at java.lang.Class.newInstance0(Class.java:374)
        at java.lang.Class.newInstance(Class.java:327)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1149)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1026)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4425)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4738)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:802)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1080)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1003)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:507)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1322)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:325)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1068)

**Comment by aharjula** [comment]
If you have the same problem you are using a very old MaximaPool version, just use a newer version, with a fixed maximapool.conf... 

But if I am guessing correctly you are using some random software that has nothing to do with MaximaPool and got an NumberFormatException from it and did not quite understand what it means, check your log-configs, there is an extra 'K' there and as a free guess you are adding K to a place that expects a raw byte-count hoping that you would not need to do your own multiplications.

Anyway please let us know where and for what you are using MaximaPool, it would be nice to hear how far it has gotten.

**Comment by musman03** [comment]
Thank you very much.. i change K with KB and resolve :)
